import { BookOpen, Mail, Ticket } from 'lucide-react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import FaqList from '@/components/FaqList';
import Link from 'next/link';

export const metadata = { title: 'Support Center', description: 'Get help with CreatorBoost through FAQs, support tickets, and email.' };
const SUPPORT_EMAIL = process.env.NEXT_PUBLIC_SUPPORT_EMAIL || 'support@creatorboost.io';

export default function SupportPage() {
  return <><Navbar /><main className="hero-gradient min-h-screen pt-24 pb-12"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><nav className="mb-8 text-sm text-gray-500"><Link href="/" className="hover:text-white">Home</Link><span className="mx-2">/</span><span className="text-white">Support</span></nav><header className="text-center mb-12"><h1 className="font-display text-4xl sm:text-5xl font-bold mb-4">How can we <span className="gradient-text">help?</span></h1><p className="text-gray-400 max-w-xl mx-auto">Browse common answers, email support, or sign in to open a ticket and keep the conversation attached to your account.</p></header><section className="grid sm:grid-cols-3 gap-4 mb-12"><a href={`mailto:${SUPPORT_EMAIL}`} className="glass rounded-2xl p-6 card-glow text-center block"><span className="w-12 h-12 rounded-xl bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center mx-auto mb-4"><Mail className="w-6 h-6 text-white" /></span><h2 className="font-semibold mb-1">Email support</h2><p className="text-sm text-gray-400 break-all">{SUPPORT_EMAIL}</p></a><Link href="/dashboard/support" className="glass rounded-2xl p-6 card-glow text-center block"><span className="w-12 h-12 rounded-xl bg-gradient-to-br from-green-500 to-emerald-500 flex items-center justify-center mx-auto mb-4"><Ticket className="w-6 h-6 text-white" /></span><h2 className="font-semibold mb-1">Support tickets</h2><p className="text-sm text-gray-400">Create and follow private account tickets</p></Link><Link href="/contact" className="glass rounded-2xl p-6 card-glow text-center block"><span className="w-12 h-12 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center mx-auto mb-4"><BookOpen className="w-6 h-6 text-white" /></span><h2 className="font-semibold mb-1">Contact form</h2><p className="text-sm text-gray-400">Send a public question or partnership request</p></Link></section><FaqList /><section className="mt-12 text-center"><h2 className="font-display text-2xl font-bold mb-2">Still need help?</h2><p className="text-sm text-gray-400 mb-4">Use the contact form or open a signed-in support ticket.</p><div className="flex flex-wrap gap-3 justify-center"><Link href="/contact" className="btn-ghost px-5 py-2.5 rounded-xl text-sm">Contact us</Link><Link href="/dashboard/support" className="btn-primary px-5 py-2.5 rounded-xl text-sm font-semibold text-white">Open support tickets</Link></div></section></div></main><Footer /></>;
}
