import { Eye, ShieldCheck, ShieldAlert, Copy, Bot, DollarSign } from 'lucide-react';
import StatCard from '@/components/StatCard';
import { formatCurrency, formatNumber } from '@/lib/utils';
import {
  CATEGORY_LABEL,
  VIEW_TRAFFIC_CATEGORIES,
  type ViewTrafficSummary,
} from '@/lib/view-eligibility';

/**
 * Admin-only traffic attribution panel.
 *
 * Renders the complete paid vs non-paid picture the admin needs:
 *   Total Views · Valid/Paid · Non-Paid · Duplicates · Bot/Fraud · Earnings
 *
 * It is fed by `admin_view_traffic_summary`, a database aggregate, so no raw
 * `views` rows travel to the browser. It shows only safe category buckets —
 * deliberately no raw visitor IP, no ip_hash, no device fingerprint, no fraud
 * score and no detection threshold.
 *
 * This component is never rendered on a creator surface.
 */
export default function AdminTrafficQuality({
  summary,
  daily,
  windowLabel,
}: {
  summary: ViewTrafficSummary;
  daily?: Array<{ day: string; total: number; paid: number; duplicates: number; fraudBlocked: number }>;
  windowLabel: string;
}) {
  const paidRate = summary.totalViews > 0
    ? Math.round((summary.paidViews / summary.totalViews) * 100)
    : 0;

  // Non-paid buckets with at least one view, largest first.
  const breakdown = VIEW_TRAFFIC_CATEGORIES
    .filter(category => category !== 'paid' && summary.byCategory[category] > 0)
    .map(category => ({ category, count: summary.byCategory[category] }))
    .sort((a, b) => b.count - a.count);

  const maxDaily = Math.max(1, ...(daily || []).map(d => d.total));

  return (
    <section className="space-y-4" aria-label="Traffic attribution">
      <div>
        <h2 className="font-display text-lg font-bold">Traffic &amp; earnings attribution</h2>
        <p className="text-xs text-gray-500">
          Every request that reached a campaign, split by whether it generated a CreatorBoost earning · {windowLabel}
        </p>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-3 gap-4">
        <StatCard
          label="Total Views"
          value={formatNumber(summary.totalViews)}
          change="All recorded traffic"
          icon={Eye}
          color="cyan"
        />
        <StatCard
          label="Valid / Paid Views"
          value={formatNumber(summary.paidViews)}
          change={`${paidRate}% of total traffic`}
          icon={ShieldCheck}
          color="green"
        />
        <StatCard
          label="Non-Paid Views"
          value={formatNumber(summary.nonPaidViews)}
          change="No creator earning"
          icon={ShieldAlert}
          color="orange"
        />
        <StatCard
          label="Duplicate Views"
          value={formatNumber(summary.duplicateViews)}
          change="Same campaign + IP within 24h"
          icon={Copy}
          color="yellow"
        />
        <StatCard
          label="Bot / Fraud Blocked"
          value={formatNumber(summary.fraudBlockedViews)}
          change="Automation, proxy & suspicious"
          icon={Bot}
          color="pink"
        />
        <StatCard
          label="Earning Amount"
          value={formatCurrency(summary.earnings)}
          change="Generated by paid views"
          icon={DollarSign}
          color="purple"
        />
      </div>

      <div className="grid lg:grid-cols-2 gap-4">
        <div className="glass rounded-2xl p-5">
          <h3 className="font-semibold mb-1">Non-paid traffic by reason</h3>
          <p className="text-xs text-gray-500 mb-4">
            Aggregated categories only — visitor IP addresses are never displayed.
          </p>
          {breakdown.length === 0 ? (
            <p className="text-sm text-gray-500 text-center py-6">No non-paid traffic in this window</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-xs text-gray-500 border-b border-white/5">
                    <th className="text-left py-2 font-medium">Reason</th>
                    <th className="text-right py-2 font-medium">Views</th>
                    <th className="text-right py-2 font-medium">Share</th>
                  </tr>
                </thead>
                <tbody>
                  {breakdown.map(({ category, count }) => (
                    <tr key={category} className="border-b border-white/5 table-row">
                      <td className="py-2.5">{CATEGORY_LABEL[category]}</td>
                      <td className="py-2.5 text-right font-mono">{formatNumber(count)}</td>
                      <td className="py-2.5 text-right text-gray-400">
                        {summary.totalViews > 0 ? `${((count / summary.totalViews) * 100).toFixed(1)}%` : '—'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        <div className="glass rounded-2xl p-5">
          <h3 className="font-semibold mb-1">Paid vs non-paid per day</h3>
          <p className="text-xs text-gray-500 mb-4">Database aggregate, last {daily?.length ?? 0} days with traffic</p>
          {!daily || daily.length === 0 ? (
            <p className="text-sm text-gray-500 text-center py-6">No traffic recorded yet</p>
          ) : (
            <div className="flex items-end gap-1.5 h-40">
              {daily.map(d => {
                const paidPct = (d.paid / maxDaily) * 100;
                const nonPaidPct = ((d.total - d.paid) / maxDaily) * 100;
                return (
                  <div key={d.day} className="flex-1 flex flex-col items-center gap-1 min-w-0">
                    <div
                      className="w-full flex flex-col justify-end h-full"
                      title={`${d.day}: ${d.total} total · ${d.paid} paid · ${d.duplicates} duplicate · ${d.fraudBlocked} bot/fraud`}
                    >
                      <div
                        className="w-full bg-orange-500/60 rounded-t-sm"
                        style={{ height: `${Math.max(nonPaidPct ? 2 : 0, nonPaidPct)}%` }}
                      />
                      <div
                        className="w-full bg-gradient-to-t from-green-500 to-emerald-400"
                        style={{ height: `${Math.max(paidPct ? 2 : 0, paidPct)}%` }}
                      />
                    </div>
                    <div className="text-[9px] text-gray-500 truncate w-full text-center">{d.day.slice(5)}</div>
                  </div>
                );
              })}
            </div>
          )}
          <div className="flex items-center gap-4 mt-3 text-[10px] text-gray-400">
            <span className="flex items-center gap-1.5">
              <span className="w-2.5 h-2.5 rounded-sm bg-emerald-400" /> Paid
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-2.5 h-2.5 rounded-sm bg-orange-500/60" /> Non-paid
            </span>
          </div>
        </div>
      </div>
    </section>
  );
}
