'use client';

import { useState } from 'react';
import { Calculator, DollarSign, Users } from 'lucide-react';

const illustrativeCpm: Record<string, number> = { tier_1: 5, tier_2: 2.75, tier_3: 1, mixed: 2.83 };

export default function CpmCalculator() {
  const [visitors, setVisitors] = useState(10_000);
  const [tier, setTier] = useState('tier_1');
  const [level, setLevel] = useState(1.25);
  const [quality, setQuality] = useState(0.75);
  const validViews = Math.max(0, Math.round(visitors * quality));
  const cpm = illustrativeCpm[tier] || illustrativeCpm.tier_1;
  const estimate = (validViews / 1000) * cpm * level;
  const effectiveCpm = validViews ? (estimate / validViews) * 1000 : 0;

  return <section id="calculator" className="relative py-24 bg-gradient-to-b from-transparent via-purple-950/20 to-transparent scroll-mt-20"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><span className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass text-xs font-medium text-purple-300 mb-4"><Calculator className="w-3 h-3" /> Illustrative calculator</span><h2 className="font-display text-4xl sm:text-5xl font-bold mb-4">Explore a <span className="gradient-text">CPM scenario</span></h2><p className="text-gray-400 max-w-2xl mx-auto">This calculator uses clearly illustrative example rates. Live earnings use the country, creator-level, cap, and fraud settings stored in the platform database at the time of each view.</p></div>
    <div className="grid lg:grid-cols-2 gap-6"><div className="glass-strong rounded-2xl p-6 sm:p-8 space-y-5"><label className="text-xs font-medium text-gray-300 block">Visitors in this scenario<input type="number" min="0" value={visitors} onChange={event => setVisitors(Math.max(0, Number.parseInt(event.target.value, 10) || 0))} className="input-field mt-2" /></label><div className="grid grid-cols-5 gap-2">{[1000, 5000, 10000, 50000, 100000].map(value => <button key={value} onClick={() => setVisitors(value)} className={`tab-btn ${visitors === value ? 'active' : ''}`}>{value >= 1000 ? `${value / 1000}K` : value}</button>)}</div><label className="text-xs font-medium text-gray-300 block">Illustrative country tier<select value={tier} onChange={event => setTier(event.target.value)} className="input-field mt-2"><option value="tier_1">Tier 1 example ($5 / 1K)</option><option value="tier_2">Tier 2 example ($2.75 / 1K)</option><option value="tier_3">Tier 3 example ($1 / 1K)</option><option value="mixed">Mixed example</option></select></label><label className="text-xs font-medium text-gray-300 block">Illustrative creator multiplier<select value={level} onChange={event => setLevel(Number(event.target.value))} className="input-field mt-2"><option value="1">Bronze (1.0×)</option><option value="1.1">Silver (1.1×)</option><option value="1.25">Gold (1.25×)</option><option value="1.5">Platinum (1.5×)</option><option value="2">Diamond (2.0×)</option></select></label><div><span className="text-xs font-medium text-gray-300 block mb-2">Illustrative eligible traffic</span><div className="grid grid-cols-4 gap-2">{[0.6, 0.75, 0.9, 0.98].map(value => <button key={value} onClick={() => setQuality(value)} className={`tab-btn ${quality === value ? 'active' : ''}`}>{Math.round(value * 100)}%</button>)}</div></div></div>
      <div className="glass-strong rounded-2xl p-6 sm:p-8 bg-gradient-to-br from-purple-500/10 to-blue-500/10 flex flex-col justify-center"><div className="flex items-center gap-2 text-xs text-gray-400 mb-1"><DollarSign className="w-3 h-3" /> Illustrative result</div><div className="text-5xl font-bold gradient-text mb-2">${estimate.toFixed(2)}</div><p className="text-xs text-gray-500 mb-6">Not a guarantee or a live payout quote.</p><div className="grid grid-cols-2 gap-3"><div className="glass rounded-2xl p-4"><div className="text-xs text-gray-400 mb-1">Eligible views</div><div className="text-2xl font-bold text-white">{validViews.toLocaleString()}</div><div className="text-xs text-gray-500 mt-1">{Math.round(quality * 100)}% of scenario traffic</div></div><div className="glass rounded-2xl p-4"><div className="text-xs text-gray-400 mb-1">Scenario CPM</div><div className="text-2xl font-bold text-purple-300">${effectiveCpm.toFixed(3)}</div><div className="text-xs text-gray-500 mt-1">Per 1,000 eligible views</div></div></div><div className="mt-5 p-4 glass rounded-xl text-xs text-gray-400"><Users className="inline w-4 h-4 text-purple-300 mr-1.5" />Actual creator earnings are recorded only after a server-side eligible view is accounted in the earnings ledger.</div></div></div>
  </div></section>;
}
