const faqs = [
  { q: 'How much can I earn?', a: 'Earnings depend on server-validated traffic, the country CPM configured by the platform, your creator level, and earning caps. The calculator on this page is illustrative; your dashboard shows recorded ledger values.' },
  { q: 'When can I withdraw?', a: 'You can request a withdrawal once your available balance meets the currently configured minimum and method limits. Requests remain pending until an authorized administrator reviews them.' },
  { q: 'How does traffic validation work?', a: 'CreatorBoost evaluates server-derived signals such as user agents, request frequency, VPN/proxy data when configured, duplicate behavior, campaign state, and earning caps. Invalid traffic is not credited.' },
  { q: 'What payment methods are supported?', a: 'Available methods, minimums, maximums, and fees are listed on the withdrawal page and are configured by the platform administrator.' },
  { q: 'How do creator levels work?', a: 'Levels are recalculated from valid view totals. The platform administrator controls the current thresholds, CPM multipliers, and optional level benefits.' },
  { q: 'Can external follows or likes be verified?', a: 'Not universally. The unlock page records browser-confirmed openings of the creator-configured task URLs; it does not claim proof of a third-party follow, like, or subscription.' },
];

export default function Faq() {
  return <section className="relative py-20 sm:py-24 bg-gradient-to-b from-transparent via-purple-950/20 to-transparent"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><span className="inline-block px-3 py-1 rounded-full glass text-xs font-medium text-purple-300 mb-3">FAQ</span><h2 className="font-display text-3xl sm:text-4xl lg:text-5xl font-bold">Got <span className="gradient-text">questions?</span></h2></div><div className="space-y-2">{faqs.map((faq, index) => <details key={faq.q} className="glass rounded-xl group" open={index === 0}><summary className="cursor-pointer p-3 sm:p-4 font-medium text-xs sm:text-sm flex items-center justify-between list-none gap-2"><span>{faq.q}</span><svg className="w-4 h-4 transition-transform group-open:rotate-180 text-purple-400 flex-shrink-0" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" /></svg></summary><div className="px-3 sm:px-4 pb-3 sm:pb-4 text-[10px] sm:text-xs text-gray-400 leading-relaxed">{faq.a}</div></details>)}</div></div></section>;
}
